# Uncomment the next line to define a global platform for your project
#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 2.6.3’
pod 'SDWebImage', '~>3.8’
 target'APITest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for APITest

  target 'APITestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'APITestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
